//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneDic
    {
        public System.Guid ID { get; set; }
        public string Surname { get; set; }
        public System.DateTime DateBrth { get; set; }
        public string Email { get; set; }
        public bool Disable { get; set; }
        public Nullable<System.DateTime> DisableCD { get; set; }
        public string DIsableAuthor { get; set; }
    }
}
